# run-abi-probe.ps1 - ABI verification for the pinned IDA backends.
#
# Generates backends/abi/expected_facts.inc from the selected backend's
# expected-<key>.json, then COMPILES backends/abi/abi_probe.cpp against
# that backend's vendored SDK headers. The probe is a compile-time contract:
# every sizeof/alignof/offsetof is a static_assert, so a layout mismatch
# fails the build with the offending fact named. Nothing is linked or run,
# so no proprietary SDK libraries or symbols are involved.
#
# The same JSON is consumed by the Rust layout tests in
# crates/reverse-ida-sys, so C++ and Rust are verified against one source
# of truth.
#
# Usage:
#   pwsh scripts/run-abi-probe.ps1 -IdaVersion 9.4   # 9.4 backend (default 9.2)
#   pwsh scripts/run-abi-probe.ps1                    # auto-find clang++
#   pwsh scripts/run-abi-probe.ps1 -Clang <path>      # explicit driver
#   pwsh scripts/run-abi-probe.ps1 -Clang <zig-path>  # zig c++ driver works
# Exit 0 = layouts verified; exit 1 = mismatch or probe failure.

param(
    [string]$Clang = "",
    [string]$IdaVersion = "9.2",
    [string]$ExpectedPath = ""
)

$ErrorActionPreference = 'Stop'

# Backend selection: -IdaVersion maps to the vendored SDK dir + fact file.
# -ExpectedPath still overrides for one-off probes.
$sdkDir = switch ($IdaVersion) {
    "9.2" { "vendor/idalib-sys/sdk" }
    "9.4" { "vendor/idalib94-sys/sdk" }
    default { throw "unsupported -IdaVersion '$IdaVersion' (expected 9.2 or 9.4)" }
}
if ($ExpectedPath -eq "") {
    $ExpectedPath = "backends/abi/expected-$($IdaVersion -replace '\.', '_').json"
}

function Find-Clang {
    param([string]$Requested)
    if ($Requested -ne "") { return $Requested }
    # Prefer a DotSlash-provisioned zig driver if present, then any clang on PATH.
    foreach ($p in @("toolchain/bin/zig", "toolchain/bin/zig.exe")) {
        if (Test-Path $p) { return (Resolve-Path $p).Path }
    }
    $cmd = Get-Command clang++ -ErrorAction SilentlyContinue
    if ($null -ne $cmd) { return $cmd.Source }
    throw "clang++ not found. Run the DotSlash bootstrap (toolchain/README.md) or pass -Clang <path>."
}

function ConvertTo-Identifier {
    param([string]$Family, [string]$Name)
    $n = $Name -replace '\.', '_'
    $f = if ($family -eq 'offsetof') { 'OFFSET' } else { $family.ToUpperInvariant() }
    "FACT_${n}_${f}".ToUpperInvariant()
}

$clang = Find-Clang $Clang
$isZig = (Split-Path -Leaf $clang) -match '^zig(\.exe)?$'
Write-Host "probe driver: $clang"
if ($isZig) {
    & $clang c++ --version | Select-Object -First 1 | Write-Host
} else {
    & $clang --version | Select-Object -First 1 | Write-Host
}

# Invoke the driver: zig needs the `c++` subcommand, clang++ does not.
$invoke = {
    param([string[]]$Args2)
    if ($isZig) {
        & $clang c++ @Args2
    } else {
        & $clang @Args2
    }
}

if (-not (Test-Path "$sdkDir/src/include/pro.h")) {
    Write-Error "SDK headers not found under $sdkDir (proprietary, not in git). Provide a local IDA $IdaVersion SDK checkout (pinned tag in the backend manifest)."
}

$expected = Get-Content $ExpectedPath -Raw | ConvertFrom-Json

# Generate expected_facts.inc: one FACT_* macro per JSON entry.
$inc = New-Object System.Text.StringBuilder
[void]$inc.AppendLine("// GENERATED by scripts/run-abi-probe.ps1 from $ExpectedPath - do not edit.")
foreach ($family in @('sizeof', 'alignof', 'offsetof')) {
    foreach ($p in $expected.probes.$family.PSObject.Properties) {
        $id = ConvertTo-Identifier -Family $family -Name $p.Name
        [void]$inc.AppendLine("#define $id $($p.Value)")
    }
}
$incPath = "backends/abi/expected_facts.inc"
Set-Content -Path $incPath -Value $inc.ToString() -Encoding ASCII

$platformFlags = @("-std=c++17", "-D__EA64__=1")
if ($IsWindows -or $env:OS -eq 'Windows_NT') {
    $platformFlags += "-D__NT__=1"
} elseif ($IsMacOS) {
    $platformFlags += "-D__MACOS__=1"
} else {
    $platformFlags += "-D__LINUX__=1"
}

$obj = "backends/abi/abi_probe.o"
$compileArgs = @()
$compileArgs += $platformFlags
$compileArgs += @("-Wno-invalid-offsetof", "-c")
$compileArgs += @("-I$sdkDir/src/include", "-Ibackends/abi", "backends/abi/abi_probe.cpp", "-o", $obj)
& $invoke $compileArgs
if ($LASTEXITCODE -ne 0) {
    Write-Host "ABI PROBE FAILED: the SDK headers do not match $ExpectedPath" -ForegroundColor Red
    exit 1
}

$count = 0
foreach ($family in @('sizeof', 'alignof', 'offsetof')) {
    $count += ($expected.probes.$family.PSObject.Properties | Measure-Object).Count
}
Write-Host "abi probe: OK ($count facts match $ExpectedPath)"
exit 0
