[package]
name = "rmcp-ida"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rmcp-core = { path = "../rmcp-core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dependencies.idalib]
path = "../../vendor/idalib"
optional = true

[dependencies.autocxx]
version = "0.27"
optional = true

[features]
idalib = ["dep:idalib", "dep:autocxx"]
default = []
